# Generated by Django 5.1.1 on 2024-10-02 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
